let express = require('express');
let path = require('path');
let cookieParser = require('cookie-parser');
let logger = require('morgan');
let cors = require('cors');
const expressOasGenerator = require('express-oas-generator');

let indexRouter = require('./routes/index');
let topicsRouter = require('./routes/topics');
let postsRouter = require('./routes/posts');
let usersRouter = require('./routes/users');

let app = express();

//Setup to generate a swagger config file
//Serves as a starter for a more extended description
//of the API (autogenerated)
expressOasGenerator.init(app,
    function (spec) {
        return spec;
    },
    'itclub-reddit-api.swagger.json',
    60 * 1000);

app.use(cors());
app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({extended: false}));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use('/topics', topicsRouter);
app.use('/posts', postsRouter);

module.exports = app;
